
api:
  insecure: true
  dashboard: true
  debug: true

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    watch: true
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true

accessLog:
  format: common
  filePath: /etc/log/access.log

log:
  level: DEBUG
  format: json

entryPoints:
  web:
    address: ":80"
